name: CI

on:
  push:
    branches:
      - "**"
      - "!/**"
  pull_request:
  workflow_dispatch:

env:
  FORCE_COLOR: 2
  NODE_LTS: 18

permissions:
  contents: deny

jobs:
  build:
    name: Build on Node ${{ matrix.node }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        node: [14, 16, 18]

    steps:
      - name:
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: run htmllint
